---
title: "Group Fou\\*R* Term Project Proposal"
subtitle: "MEF University - BDA 503 Essentials of Data Analytics - Fall 2018"
output: html_document
---

We will export trade data of Turkey from trademap.org website which provides trade statistics for international business development.

Our aim is to analyze Turkey’s trade characteristics by product groups against 10 selected countries (G7 countries and Russia, India, China) and to summarize the Turkey’s overall trade statistics in this frame.

We will start with exporting total annual value of export and import of Turkey and quantities by product group against the target selected countries in the website. These data will include 5 years period from 2013 to 2017. Secondly, since the exported data are consist of 40 excel files (10 countries(trade against 10 countries) * 2 trade type (export and import) * 2 metric (trade value and trade quantity)), we will combine these files. Then, we will clean the data if needed and finally, we will analyze the data.

Through the analysis and visualization of the data, our object is to use explanatory analysis and visualization skills with data manipulation functions of like dplyr, reshape etc and visualition tools like ggplot, shiny and any other packages we will explore.